UPDATE `projects` SET `created_at` = `created_at` || 'Z' WHERE `created_at` NOT LIKE '%Z';--> statement-breakpoint
UPDATE `projects` SET `updated_at` = `updated_at` || 'Z' WHERE `updated_at` NOT LIKE '%Z';--> statement-breakpoint
UPDATE `agents` SET `created_at` = `created_at` || 'Z' WHERE `created_at` NOT LIKE '%Z';--> statement-breakpoint
UPDATE `agents` SET `updated_at` = `updated_at` || 'Z' WHERE `updated_at` NOT LIKE '%Z';--> statement-breakpoint
UPDATE `messages` SET `created_at` = `created_at` || 'Z' WHERE `created_at` NOT LIKE '%Z';--> statement-breakpoint
UPDATE `alert_channels` SET `created_at` = `created_at` || 'Z' WHERE `created_at` NOT LIKE '%Z';--> statement-breakpoint
UPDATE `alert_channels` SET `updated_at` = `updated_at` || 'Z' WHERE `updated_at` NOT LIKE '%Z';--> statement-breakpoint
UPDATE `scheduled_tasks` SET `created_at` = `created_at` || 'Z' WHERE `created_at` NOT LIKE '%Z';--> statement-breakpoint
UPDATE `scheduled_tasks` SET `updated_at` = `updated_at` || 'Z' WHERE `updated_at` NOT LIKE '%Z';--> statement-breakpoint
UPDATE `scheduled_tasks` SET `last_run_at` = `last_run_at` || 'Z' WHERE `last_run_at` IS NOT NULL AND `last_run_at` NOT LIKE '%Z';--> statement-breakpoint
UPDATE `scheduled_tasks` SET `scheduled_at` = `scheduled_at` || 'Z' WHERE `scheduled_at` IS NOT NULL AND `scheduled_at` NOT LIKE '%Z';
